config/urls.py
from django.contrib import admin
from django.urls import include, path

from stellar_poe.views import HomeView

admin.site.site_title = "Stellar POE"
admin.site.site_header = "Stellar POE"

urlpatterns = [
    path("super/", admin.site.urls),
    path("", include("stellar_poe.users.urls", namespace="auth")),
    path("", HomeView.as_view(), name="home"),
    path("", include("stellar_poe.transactions.urls", namespace="transactions")),
]

stellar_poe/transactions/urls.py
from django.urls import path

from . import views

app_name = "transactions"


urlpatterns = [
    path("transactions/", views.TransactionListView.as_view(), name="transaction-list"),
    path(
        "transactions/create/",
        views.TransactionCreateView.as_view(),
        name="transaction-create",
    ),
    path(
        "transactions/<uuid:id>/",
        views.TransactionDetailView.as_view(),
        name="transaction-detail",
    ),
]

stellar_poe/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "users"


urlpatterns = [
    path(
        "login",
        auth_views.LoginView.as_view(template_name="login.html", success_url="/"),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "change-password",
        auth_views.PasswordChangeView.as_view(
            template_name="users/change_password.html", success_url="/"
        ),
        name="change-password",
    ),
    path("profile", views.UserDetailView.as_view(), name="profile"),
    path("signup", views.SignupView.as_view(), name="signup"),
]

stellar_poe/transactions/models.py
import hashlib
import uuid

from django.conf import settings
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.utils.translation import ugettext_lazy as _
from model_utils.models import TimeStampedModel


class Transaction(TimeStampedModel):

    id = models.UUIDField(default=uuid.uuid4, primary_key=True)

    sender = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=_("Sender"),
        related_name="+",
    )

    recipient = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=_("Recipient"),
        related_name="+",
    )

    file = models.FileField(_("File"), upload_to="transaction/%Y/%m/%d/")
    file_hash = models.CharField(max_length=32, editable=False)
    stellar_response_data = JSONField(
        _("Stellar transaction response data"), null=True, blank=True
    )
    is_submitted = models.BooleanField(default=False)
    stellar_transaction_link = models.URLField(null=True)
    stellar_transaction_hash = models.CharField(max_length=64, null=True)

    message = models.CharField(_("Message"), max_length=100)

    class Meta:
        verbose_name = _("Transaction")
        verbose_name_plural = _("Transactions")
        ordering = ("-created",)

    def __str__(self):
        return self.message

    def compute_hash_file(self):
        self.file_hash = hashlib.md5(self.file.read()).hexdigest()

stellar_poe/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _

from stellar_poe.stellar import utils


class User(AbstractUser):

    stellar_seed = models.CharField(
        _("Stellar seed"), max_length=100, null=True, blank=True
    )
    stellar_key = models.CharField(
        _("Stellar key"), max_length=100, null=True, blank=True
    )

    class Meta:
        db_table = "auth_user"

    def gen_address(self):
        self.stellar_seed, self.stellar_key = utils.create_new_address()

    def ask_for_initial_balance(self):
        return utils.ask_for_coins(self.stellar_key)

stellar_poe/transactions/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext as _

from .models import Transaction


User = get_user_model()


class TransactionForm(forms.ModelForm):

    MAX_SIZE = 10_485_760  # 10Mb

    class Meta:
        model = Transaction
        fields = ("recipient", "message", "file")

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        super().__init__(*args, **kwargs)
        self.fields["recipient"].queryset = User.objects.exclude(id=request.user.id)

    def clean_file(self):
        file_ = self.cleaned_data.get("file")
        if file_ and file_.size < self.MAX_SIZE:
            return file_
        else:
            raise forms.ValidationError(_("File too big, max file size is 10Mb"))

stellar_poe/users/forms.py
from django import forms
from django.utils.translation import gettext as _

from .models import User


class SignupForm(forms.ModelForm):

    confirm_password = forms.CharField(
        label=_("Confirm password"), widget=forms.PasswordInput, required=True
    )

    class Meta:
        model = User
        fields = ("username", "password", "confirm_password")
        widgets = {"password": forms.PasswordInput}

    def clean_confirm_password(self):
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")
        if password and confirm_password:
            if password != confirm_password:
                raise forms.ValidationError(_("Password doesn't match"))
        return confirm_password

    def save(self, commit=True):
        user = super().save(commit=commit)
        user.is_active = True
        user.set_password(self.cleaned_data.get("password"))
        user.gen_address()
        user.ask_for_initial_balance()
        user.save()
        return user

stellar_poe/transactions/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView

from stellar_poe.stellar import utils

from . import forms
from .models import Transaction


class TransactionCreateView(LoginRequiredMixin, CreateView):

    template_name = "transactions/transaction-create.html"
    model = Transaction
    success_url = reverse_lazy("transactions:transaction-list")
    form_class = forms.TransactionForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"request": self.request})
        return kwargs

    def form_valid(self, form):
        # TODO: move this logic to another module
        transaction = form.save(commit=False)
        transaction.sender = self.request.user
        transaction.compute_hash_file()
        response = super().form_valid(form)
        res = utils.create_transaction(
            transaction.sender.stellar_seed,
            transaction.recipient.stellar_key,
            transaction.file_hash,
        )
        transaction.stellar_response_data = res
        transaction.is_submitted = True
        transaction.stellar_transaction_link = res["_links"]["transaction"]["href"]
        transaction.stellar_transaction_hash = res["hash"]
        transaction.save()
        return response


class TransactionListView(LoginRequiredMixin, ListView):

    template_name = "transactions/transaction-list.html"
    model = Transaction
    paginate_by = settings.PAGINATION_DEFAULT_PAGE_SIZE
    context_object_name = "transactions"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(Q(sender=self.request.user) | Q(recipient=self.request.user))
            .select_related("recipient", "sender")
        )


class TransactionDetailView(LoginRequiredMixin, DetailView):

    template_name = "transactions/transaction-detail.html"
    model = Transaction
    context_object_name = "transaction"
    pk_url_kwarg = "id"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(Q(sender=self.request.user) | Q(recipient=self.request.user))
        )

stellar_poe/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView

from . import forms
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):

    template_name = "users/profile.html"
    model = User
    context_object_name = "user"

    def get_object(self):
        return self.request.user


class SignupView(CreateView):

    template_name = "users/signup.html"
    form_class = forms.SignupForm
    success_url = reverse_lazy("home")

stellar_poe/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class HomeView(LoginRequiredMixin, TemplateView):

    template_name = "home.html"

stellar_poe/templates/_filter.html
{% load i18n crispy_forms_tags %}
<style>
  .filter-form .form-group {
    margin-right: 10px;
    padding-bottom: 5px;
  }
  .filter-form .form-control {
    margin-left: 10px;
  }
  .filter-form button {
    margin-bottom: 5px;
  }
</style>
<div class="row">
  <div class="col-md-12">
    <form class="form-inline filter-form">
      {% crispy filter.form filter.helper %}
      <button class="btn btn-outline-secondary" type="submit">
        <i class="fas fa-search"></i>
        {% trans 'Filter' %}
      </button>
    </form>
  </div>
</div>
<br/>

stellar_poe/templates/_pagination.html
{% load pagination_tags i18n %}
{% if page_obj.paginator.num_pages > 1 %}
<nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ request|querystring_without_page }}">
        <i class="fas fa-angle-left"></i>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">
        <i class="fas fa-angle-left"></i>
      </a>
    </li>
    {% endif %}
    {% for page_number in page_obj|pagination_range:10 %}
    {% if page_number == page_obj.number %}
    <li class="page-item active disabled">
      <a class="page-link" href="#">{{ page_number }}</a>
    </li>
    {% elif page_number == "..." %}
    <li class="page-item disabled">
      <a class="page-link" href="#">{{ page_number }}</a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_number }}&{{ request|querystring_without_page }}">
        <span>{{ page_number }}</span>
      </a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ request|querystring_without_page }}">
        <i class="fas fa-angle-right"></i>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">
        <i class="fas fa-angle-right"></i>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

stellar_poe/templates/base.html
{% load staticfiles i18n humanize %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static "vendor/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "vendor/css/fontawesome-all.min.css" %}">
    <link rel="stylesheet" href="{% static "vendor/css/bootstrap-datepicker3.min.css" %}">
    <link rel="stylesheet" href="{% static "css/dashboard.css" %}">
    {% block css %}{% endblock %}

    <title>Stellar POE | {{ title }}</title>

  </head>
  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'home' %}">Stellar Proof Of Evidence</a>
      <!-- <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> -->
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="{% url "users:logout" %}">
            <i class="fas fa-sign-out-alt"></i> {% trans "Sign out" %}
          </a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link {% if request.path == "/" %}active{% endif %}" href="{% url "home" %}">
                  <span class="fas fa-home"></span>
                  {% trans "Dashboard" %} <span class="sr-only">(current)</span>
                </a>
              </li>
            </ul>

            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link {% if "transactions" in request.path %}active{% endif %}" href="{% url "transactions:transaction-list" %}">
                  <span class="fas fa-exchange-alt"></span>
                  {% trans "Transactions" %}
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>{% trans "Reporting" %}</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span class="fas fa-plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span class="fas fa-chart-line"></span>
                  Sample report
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span class="fas fa-chart-bar"></span>

                  Sample report 2
                </a>
              </li>
            </ul>
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>{% trans "Settings" %}</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span class="fas fa-plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="{% url "users:profile" %}">
                  <span class="fas fa-user"></span>
                  {% trans "Profile" %}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path == "/change-password" %}active{% endif %}" href="{% url "users:change-password" %}">
                  <span class="fas fa-key"></span>
                  {% trans "Change password" %}
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
          {% block content %}{% endblock content %}
          <br/>
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "vendor/js/jquery-3.2.1.min.js" %}"></script>
    <script src="{% static "vendor/js/bootstrap.min.js" %}"></script>
    <script src="{% static "vendor/js/bootstrap-datepicker.min.js" %}"></script>

    {% block javascript %}{% endblock %}
  </body>
</html>

stellar_poe/templates/home.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <div class="row text-center">
    <div class="col-md-12">
      <div class="jumbotron">
        <div class="row">
          <div class="col-md-12">
            Hello there
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

stellar_poe/templates/login.html
{% load i18n staticfiles crispy_forms_tags %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% trans "Signin" %}</title>

    <!-- Bootstrap core CSS -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static "vendor/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "vendor/css/fontawesome-all.min.css" %}">
  </head>

  <body>

    <div class="container">
      <br/>
      <br/>

      <div class="row">
        <div class="col-md-12 text-center">
          <h1>Stellar POE</h1>
          <p>
            <i class="fas fa-8x fa-user-secret"></i>
          </p>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4 offset-md-4">
          <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-lg btn-primary btn-block" type="submit">
              <i class="fas fa-sign-in-alt"></i> {% trans "Sign in" %}
            </button>
            <a class="btn btn-lg btn-secondary btn-block" href="{% url "users:signup" %}">
              {% trans "Create a new account" %}
            </a>
          </form>
        </div>
      </div>

    </div>
  </body>
</html>

stellar_poe/templates/transactions/transaction-create.html
{% extends "base.html" %}
{% load i18n form_tags %}
{% block content %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">{% trans "New transaction" %}</h1>
  </div>

  <div class="row">
    <div class="col-md-12">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-6">
            {% field form.recipient %}
            {% field form.message %}
            {% field form.file %}
          </div>
          <div class="col-md-6">
          </div>
        </div>
        <button class="btn btn-outline-primary" type="submit">
          <i class="fas fa-save"></i>
          {% trans "Save" %}
        </button>
        <a class="btn btn-outline-secondary" href="{% url "transactions:transaction-list" %}">
          {% trans "Cancel" %}
        </a>
      </form>
    </div>
  </div>
{% endblock content %}

stellar_poe/templates/transactions/transaction-detail.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">{{ transaction.message }}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <table class="table table-bordered table-striped">
        <tbody>
          <tr>
            <td>{% trans "Recipient" %}</td>
            <td>{{ transaction.recipient.username }}</td>
          </tr>
          <tr>
            <td>{% trans "Message" %}</td>
            <td>{{ transaction.message }}</td>
          </tr>
          <tr>
            <td>{% trans "File" %}</td>
            <td>
              <a href="{{ transaction.file.url }}">
                {{ transaction.file.url }}
              </a>
            </td>
          </tr>
          <tr>
            <td>{% trans "File hash" %}</td>
            <td>{{ transaction.file_hash }}</td>
          </tr>
          <tr>
            <td>{% trans "Stellar transaction link" %}</td>
            <td>
              {% if transaction.is_submitted %}
                <a href="{{ transaction.stellar_transaction_link }}" target="_blank">
                  {{ transaction.stellar_transaction_hash }}
                </a>
              {% else %}
                {% trans "Transaction not submitted" %}
              {% endif %}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock content %}

stellar_poe/templates/transactions/transaction-list.html
{% extends "base.html" %}
{% load i18n static %}
{% block content %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Transactions</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <a class="btn btn-sm btn-outline-secondary" href="{% url "transactions:transaction-create" %}">
          <i class="fas fa-plus"></i>
          {% trans "New transaction" %}
        </a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <td>{% trans "Sender" %}</td>
            <td>{% trans "Recipient" %}</td>
            <td>{% trans "Message" %}</td>
            <td>{% trans "File" %}</td>
            <td>{% trans "File hash" %}</td>
            <td>{% trans "Stellar transaction link" %}</td>
            <td></td>
          </tr>
        </thead>
        <tbody>
          {% for transaction in transactions %}
            <tr>
              <td>
                {{ transaction.sender.username }}
              </td>
              <td>
                {{ transaction.recipient.username }}
              </td>
              <td>{{ transaction.message }}</td>
              <td>
                <a href="{{ transaction.file.url }}">
                  {{ transaction.file.url }}
                </a>
              </td>
              <td>{{ transaction.file_hash }}</td>
              <td>
                {% if transaction.is_submitted %}
                  <a href="{{ transaction.stellar_transaction_link }}" target="_blank">
                    {{ transaction.stellar_transaction_hash }}
                  </a>
                {% else %}
                  {% trans "Transaction not submitted" %}
                {% endif %}
              </td>
              <td>
                <a href="{% url "transactions:transaction-detail" transaction.id %}">{% trans "View" %}</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-md-12">
      {% include "_pagination.html" %}
    </div>
  </div>
{% endblock content %}

stellar_poe/templates/users/change_password.html
{% extends 'base.html' %}
{% load i18n crispy_forms_tags %}
{% block content %}
  <div class="row">
    <div class="col-md-6">
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-outline-primary" type="submit">
          <i class="fas fa-save"></i>
          {% trans 'Save' %}
        </button>
        <a class="btn btn-outline-secondary" href="{% url 'home' %}">
          {% trans 'Cancel' %}
        </a>
      </form>
    </div>
  </div>
{% endblock content %}

stellar_poe/templates/users/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">{% trans "Profile" %}</h1>
  </div>
  <div class="row">
    <div class="col-md-6">
      <table class="table table-striped table-bordered">
        <tr>
          <td>
            {% trans "Username" %}
          </td>
          <td>{{ user.username }}</td>
        </tr>
        <tr>
          <td>
            {% trans "Stellar Seed" %}
          </td>
          <td>{{ user.stellar_seed|default_if_none:"" }}</td>
        </tr>
        <tr>
          <td>
            {% trans "Stellar key" %}
          </td>
          <td>{{ user.stellar_key|default_if_none:"" }}</td>
        </tr>
      </table>
    </div>
  </div>
{% endblock content %}

stellar_poe/templates/users/signup.html
{% load i18n staticfiles crispy_forms_tags %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% trans "Sign up" %}</title>

    <!-- Bootstrap core CSS -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static "vendor/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "vendor/css/fontawesome-all.min.css" %}">
  </head>

  <body>

    <div class="container">
      <br/>
      <br/>

      <div class="row">
        <div class="col-md-12 text-center">
          <h1>Stellar POE</h1>
          <p>
            <i class="fas fa-8x fa-user-secret"></i>
          </p>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4 offset-md-4">
          <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-lg btn-primary btn-block" type="submit">
              <i class="fas fa-sign-in-alt"></i> {% trans "Sign up" %}
            </button>
          </form>
        </div>
      </div>

    </div>
  </body>
</html>